### PR TITLE
Enemy animation class

### PR DESCRIPTION
**Pull request by Jericho-R-Orienza**
This PR includes the following:
- sprite sheets for enemy dragon
- a react view to test and demo dragon animations
   - css file for react view
- a javascript file (the animation class) that deals with the logic in animating the dragon sprite sheets

This class will be used when making the game view.

TESTING NOTE: there are no App.jsx changes in this PR, if you would like to test it and view the animation you will have to...
- import "EnemyAnimation" from "enemy.jsx" in App.jsx
- comment out everything within App.jsx return() 
   - put <EnemyAnimation /> inside App.jsx return()

### CODE REVIEW

**Comment by AnimishTemple** [comment]
Re-commenting the above, just so it's easily noticeable when testing:

TESTING NOTE: there are no App.jsx changes in this PR, if you would like to test it and view the animation you will have to...

    import "EnemyAnimation" from "enemy.jsx" in App.jsx
    comment out everything within App.jsx return()
        put inside App.jsx return()

**Review by AnimishTemple — APPROVED** [review]
Works as intended! Good job Jericho

**Comment by AnimishTemple** [comment]
I can merge once Prince looks at it

**Comment by Prince-Nahar** [comment]
Looks good. Good work!

**Review by Prince-Nahar — APPROVED** [review]

**Pull request merged**
